In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
w = np.array([10, 20])

print(w - a)

np.sum(w - a, axis=0)

[[ 9 18]
 [ 7 16]]


array([16, 34])

In [9]:
np.dot(a, w)

array([ 50, 110])

In [52]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

y = np.array([1, 10, 100])

c = np.array([False, True, False])

# y[c] = 0

z = np.where(c, 0, y)

(x.T * z).T

array([[  1,   2,   3],
       [  0,   0,   0],
       [700, 800, 900]])

In [48]:
s = np.array([0.1, 0.5, 0.9, 1, 2])
s >= 1

array([False, False, False,  True,  True])